SQL Fix Closes #104
clemsonMakerspace/CATS pull request #121
Opened 2017-02-22 02:28 UTC by gmross

These are the fixes that I managed to pull together based on Owen's comments in #104 (SQL Fixes).  I believe this closes the issue(s) addressed.

2017-02-22 02:57 UTC, r3cebarnett submitted a review, later dismissed

2017-02-22 06:09 UTC, ophilli requested changes

2017-02-22 06:09 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
> +    authdata = cursor.fetchone()
We don't want to download all three cols - just the one that is appropriate for our machine type.

2017-02-22 06:09 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
> -        if(auth[machineType] != 1):
The new line 17 should replace this logic.

2017-03-01 02:33 UTC, r3cebarnett commented
Everything that I did can be seen in commit# 42577a7

Okay so I fixed how we get the stuffs from the SQL. There were a few things that were pretty screwy. So now we look up "authType" using "PiHostname" in the SQL, then look up the variable that authType is for ID in user. This is what is returned in machineAuth. For some reason, we had machineAuth returning the current machine, which makes no sense as we try to use it as a boolean later in the program but also as a machinetype in the SQL call in line 54, 55. This is like really stupid and needs to be fixed but I'm more concerned about fixing the algorithm than an event log. @gacosta, @gmross, and I will discuss a better way for us to do this. Also I'd like us to clear up a lot of the formatting for our code. It's very sporadic and all over the place where functions are. It'd be a lot of cleaning to do but I'd really like us to reorganize where we put functions. I found myself searching for a long time trying to find a specific function.

Anyways /rant. @ophilli does this fix the issue you had or do you have any further comments?

2017-03-01 03:14 UTC, ophilli requested changes
Your changes look fine to me - except for the t1String issue.

2017-03-01 03:14 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
> +    cursor.execute("SELECT " + authType + " FROM USER WHERE t1String = " + id) #getting user w/ the id    #might need to modify
t1String is not a column in the `catsadmin`.`users` table on watt.cuMaker.space.

Will accept once this issue is resolved. Might be resolved by adjusting code, or simply adding the column to the table. I'll leave this up to the software team to review.

2017-03-01 03:16 UTC, ophilli approved these changes

2017-03-01 03:16 UTC, merged