Optional Keypad Implemented
clemsonMakerspace/CATS pull request #123
Opened 2017-03-02 03:07 UTC by gacosta1

The optional keypad has been implemented.

2017-03-03 03:16 UTC, r3cebarnett approved these changes

2017-03-03 03:45 UTC, gmross approved these changes

2017-04-05 05:31 UTC, ophilli requested changes
Just a couple style comments really. I assume you tested this code - we really need unit testing . . .

2017-04-05 05:31 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
>      data = cursor.fetchone() #fetching data into array
On line 10 you did some shenanigans to get currMachineID into the SQL query - why not here?

2017-04-05 05:31 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
> +    return(currMachineID)
Do our style conventions call for return() or just return? All the functions below this use return.

2017-04-05 05:31 UTC, ophilli commented on Software/scan_key/AuthenticationSQL.py
> +    cursor.execute("SELECT user2fa FROM USER WHERE t1String = " + idString) #getting user w/ the opt$
See line 64

2017-04-05 05:31 UTC, ophilli commented on Software/scan_key/main.py
> +    config.read(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'config.cfg')) #actually read the config file
Lol that's some magic

2017-04-05 12:59 UTC, gacosta1 commented on Software/scan_key/AuthenticationSQL.py
>      data = cursor.fetchone() #fetching data into array
There's something with the encoding of the string that won't allow it to be used in the SQL instruction so I had to use '%s'. Or I could do
" ' " + currMachineID + " ' "

2017-04-05 12:59 UTC, gacosta1 commented on Software/scan_key/AuthenticationSQL.py
> +    return(currMachineID)
I'll make sure to change the return values to have parentheses around them

2017-04-05 15:13 UTC, ophilli approved these changes

2017-04-05 15:14 UTC, ophilli commented
Approved - do you still want @thorbrockman to review or should I merge?

2017-04-05 15:24 UTC, gacosta1 commented
@ophilli Merge please!

2017-04-05 15:34 UTC, merged