Brad's CATSBS Work for Makerday
clemsonMakerspace/CATS pull request #144
Opened 2017-04-27 06:54 UTC by ophilli

@jhord I've started a commit to merge all of your work into the repo. If you want to commit all this code yourself so that it is on your account please let me know - if not, please review the pull request and merge it.

2017-04-27 09:55 UTC, jhord requested changes
plz do the needful

2017-04-27 09:56 UTC, jhord requested changes
plz do the needful

2017-05-11 18:52 UTC, ophilli commented
@jhord plz do the needful and review this stuff

2017-05-11 21:41 UTC, jhord approved these changes

2017-05-11 21:42 UTC, merged