Cfgv1 Closes #61
clemsonMakerspace/CATS pull request #96
Opened 2017-01-31 01:33 UTC by r3cebarnett

TL;DR
Added a bare config file basically
Added some suggestions
Cleaned up the connection part of errorsql.py

Lemme know if everything looks alright.

2017-01-31 01:51 UTC, ophilli requested changes
Looks great @r3cebarnett! Please add a new-line to config.cfg though!

2017-01-31 01:51 UTC, ophilli commented on Software/scan_key/config.cfg
> +	password =
Please add a newline here

2017-01-31 01:51 UTC, ophilli commented on Software/scan_key/ErrorSQL.py
> +	config = configparser.RawConfigParser() #instantiate config reader
Long term this file should be made a class and these variables should be pulled into __init__().

2017-01-31 01:56 UTC, r3cebarnett commented on Software/scan_key/ErrorSQL.py
> +	config = configparser.RawConfigParser() #instantiate config reader
I agree with this, however I think it should just be made into a new file called sql.py or something and then we can have errorsql.py handle errors and authsql.py handle authentication or something.

Or have send and get methods in sql.py

2017-01-31 01:57 UTC, r3cebarnett commented on Software/scan_key/config.cfg
> +	password =
Done I think

2017-01-31 01:59 UTC, r3cebarnett reviewed
Updated.

2017-01-31 02:07 UTC, ophilli commented
@r3cebarnett Thanks for updating.

It's a style convention from C - It also fixes a couple of github "warnings". Check [this](https://www.quora.com/Why-is-it-a-common-practice-to-put-a-new-line-at-the-end-of-a-source-code-file) out for more info.

2017-01-31 02:17 UTC, gacosta1 requested changes
@gmross Please review this before Wednesday morning. Feel free to express your thoughts!

2017-01-31 02:17 UTC, ophilli commented
@r3cebarnett Check this out - I just had a major bug on my own code with this. http://stackoverflow.com/questions/13800515/cant-load-relative-config-file-using-configparser-from-sub-directory

2017-01-31 02:18 UTC, gacosta1 submitted a review, later dismissed

2017-01-31 02:19 UTC, ophilli submitted a review, later dismissed

2017-01-31 03:52 UTC, r3cebarnett commented
@ophilli 
do you want me to go back and implement that?

2017-01-31 04:16 UTC, ophilli commented
@r3cebarnett That would be best. This will cause a major issue for CATS down the road if we don't fix it now.

2017-01-31 04:27 UTC, r3cebarnett commented
@ophilli Should I make a config folder or just keep it like it is?

2017-01-31 04:29 UTC, ophilli commented
I'd say leave it how it is - `software/config.cfg` is a lot cleaner than `software/config/config.cfg`

2017-01-31 04:31 UTC, ophilli reviewed
Perfect! Thanks for implementing this @r3cebarnett.

2017-01-31 04:31 UTC, r3cebarnett commented
No problem! @ophilli

2017-02-01 02:25 UTC, gmross approved these changes

2017-02-01 02:29 UTC, ophilli commented
Excellent. Please merge at your earliest convenience @gmross.

2017-02-01 05:32 UTC, merged