requirements.txt v0.1
clemsonMakerspace/CATS pull request #98
Opened 2017-02-01 04:50 UTC by gmross

Attempted to create a requirements.txt file.  From what I could read, it consists of the arguments in the commands for setup.sh (the package names).  Not entirely sure if any of it is right

2017-02-01 05:00 UTC, ophilli commented
@gmross Looks awesome man! Great job. I've got a few comments though - Please review and implement [this.](https://github.com/waffleio/waffle.io/wiki/FAQs#prs-connect-keywords)

Additionally, please review the best practices for requirements.txt [here.](https://devcenter.heroku.com/articles/python-pip)

2017-02-01 05:03 UTC, ophilli requested changes

2017-02-01 05:03 UTC, ophilli commented on Software/requirements.txt
> +python3>=3.4,<3.5
None of the packages above here belong in requirements.txt.

You're writing a [pip requirements file](https://pip.pypa.io/en/stable/user_guide/#requirements-files), and pip is the package manager for python. That means that the only things we can specify are things that pip can install for us.

Finally, please review the best practices [here](https://devcenter.heroku.com/articles/python-pip) and implement them below.

2017-02-01 05:41 UTC, ophilli commented
Great job @gmross! I'm going to let somebody else finish this review. 

Looks like the link I gave you on connection words wasn't fully complete - try using a github [closing](https://help.github.com/articles/closing-issues-via-commit-messages/) keyword. This keyword will close the issue when we merge this PR.

2017-02-02 23:00 UTC, r3cebarnett commented
Looks good to me! If I missed something it will turn up very soon anyways.

2017-02-02 23:01 UTC, r3cebarnett approved these changes

2017-02-05 05:19 UTC, ophilli approved these changes

2017-02-05 05:19 UTC, merged